<?php

/**
 * This is the model base class for the table "estatus".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Estatus".
 *
 * Columns in table "estatus" available as properties of the model,
 * followed by relations of table "estatus" available as properties of the model.
 *
 * @property integer $idESTATUS
 * @property string $nombre
 * @property integer $TIPO_ESTADO_idTIPO_ESTADO
 *
 * @property Cliente[] $clientes
 * @property TipoEstatus $tIPOESTADOIdTIPOESTADO
 * @property Usuario[] $usuarios
 */
abstract class BaseEstatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'estatus';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Estatus|Estatuses', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('TIPO_ESTADO_idTIPO_ESTADO', 'required'),
			array('TIPO_ESTADO_idTIPO_ESTADO', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>45),
			array('nombre', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idESTATUS, nombre, TIPO_ESTADO_idTIPO_ESTADO', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'clientes' => array(self::HAS_MANY, 'Cliente', 'ESTATUS_idESTATUS'),
			'tIPOESTADOIdTIPOESTADO' => array(self::BELONGS_TO, 'TipoEstatus', 'TIPO_ESTADO_idTIPO_ESTADO'),
			'usuarios' => array(self::HAS_MANY, 'Usuario', 'ESTATUS_idESTATUS'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idESTATUS' => Yii::t('app', 'Id Estatus'),
			'nombre' => Yii::t('app', 'Nombre'),
			'TIPO_ESTADO_idTIPO_ESTADO' => null,
			'clientes' => null,
			'tIPOESTADOIdTIPOESTADO' => null,
			'usuarios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idESTATUS', $this->idESTATUS);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('TIPO_ESTADO_idTIPO_ESTADO', $this->TIPO_ESTADO_idTIPO_ESTADO);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}