<?php

/**
 * This is the model base class for the table "tipo_estatus".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoEstatus".
 *
 * Columns in table "tipo_estatus" available as properties of the model,
 * followed by relations of table "tipo_estatus" available as properties of the model.
 *
 * @property integer $idTIPO_ESTATUS
 * @property string $nombre
 *
 * @property Estatus[] $estatuses
 */
abstract class BaseTipoEstatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipo_estatus';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TipoEstatus|TipoEstatuses', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'length', 'max'=>45),
			array('nombre', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idTIPO_ESTATUS, nombre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'estatuses' => array(self::HAS_MANY, 'Estatus', 'TIPO_ESTADO_idTIPO_ESTADO'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idTIPO_ESTATUS' => Yii::t('app', 'Id Tipo Estatus'),
			'nombre' => Yii::t('app', 'Nombre'),
			'estatuses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idTIPO_ESTATUS', $this->idTIPO_ESTATUS);
		$criteria->compare('nombre', $this->nombre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}