<?php

/**
 * This is the model base class for the table "tipo_privilegio".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoPrivilegio".
 *
 * Columns in table "tipo_privilegio" available as properties of the model,
 * followed by relations of table "tipo_privilegio" available as properties of the model.
 *
 * @property integer $idTIPO_PRIVILEGIO
 * @property string $nombre
 *
 * @property Privilegios[] $privilegioses
 */
abstract class BaseTipoPrivilegio extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipo_privilegio';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TipoPrivilegio|TipoPrivilegios', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('nombre', 'length', 'max'=>45),
			array('idTIPO_PRIVILEGIO, nombre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'privilegioses' => array(self::HAS_MANY, 'Privilegios', 'TIPO_PRIVILEGIO_idTIPO_PRIVILEGIO'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idTIPO_PRIVILEGIO' => Yii::t('app', 'Id Tipo Privilegio'),
			'nombre' => Yii::t('app', 'Nombre'),
			'privilegioses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idTIPO_PRIVILEGIO', $this->idTIPO_PRIVILEGIO);
		$criteria->compare('nombre', $this->nombre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}