<?php

/**
 * This is the model base class for the table "rol".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Rol".
 *
 * Columns in table "rol" available as properties of the model,
 * followed by relations of table "rol" available as properties of the model.
 *
 * @property integer $idROL
 * @property string $nombre
 *
 * @property Privilegios[] $privilegioses
 * @property Usuario[] $usuarios
 */
abstract class BaseRol extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'rol';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Rol|Rols', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('idROL', 'required'),
			array('idROL', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>45),
			array('nombre', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idROL, nombre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'privilegioses' => array(self::HAS_MANY, 'Privilegios', 'ROL_idROL'),
			'usuarios' => array(self::HAS_MANY, 'Usuario', 'ROL_idROL'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idROL' => Yii::t('app', 'Id Rol'),
			'nombre' => Yii::t('app', 'Nombre'),
			'privilegioses' => null,
			'usuarios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idROL', $this->idROL);
		$criteria->compare('nombre', $this->nombre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}